### ISSUE TITLE
Settings의 내용중 device의 이름이 암꺼나 나옴

### ISSUE THREAD

**Issue by wonchul** [browser2mobile/chrome#1]
![_016](https://cloud.githubusercontent.com/assets/1332939/5638720/6c7cedd6-964e-11e4-98ae-be5ca37391b7.png)

Settings의 내용중 device의 이름 어떤 기준에서 나오는지 모르겠으나
나의 모바일 이름도 아니고 이름을 변경 가능하지도 않음

이왕이면 변경 가능 했으면 좋겠고 안되면 사용자가 알수 있는 이름이면 됨

**Comment by yidonguk** [comment]
모델명(디바이스아이디) 형식으로 나오도록 수정함.
